config/routes.rb
Trendingph::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts
  resources :votes, only: [:create]

  root to: 'posts#index'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  has_many :votes

  before_validation :add_http
  after_create :add_author_vote

  validates :user_id, presence: true
  validates :url, presence: true, url: true
  validates :title, presence: true
  GRAVITY = 1.5

  def voted_by?(user)
    self.votes.find_by(user_id: user.id)
  end

  def vote_from!(user)
    self.votes.create!(user_id: user.id)
    self.increment!(:upvote)
  end

  def self.list
    if Rails.env.production?
      time = "(EXTRACT(EPOCH FROM CURRENT_TIMESTAMP - created_at)/3600)"
      denom = "(#{time}+2)^#{GRAVITY}"
    else
      time = "((strftime('%s', current_timestamp) - strftime('%s', created_at))/3600)"
      denom = "(#{time}+2)*(#{time}*(#{GRAVITY}-1))"
    end
    score_query = "(upvote -1)/(#{denom})"

    order("#{score_query} DESC")
  end

  private
    def add_http
      if(!self.url.starts_with?("http"))
        self.url.insert(0, "http://")
      end
    end

    def add_author_vote
      self.votes.create(user: self.user)
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :votes

  before_save :create_remember_token
  before_save { self.email.downcase! }

  has_secure_password

  validates :username, presence: true, uniqueness: { case_sensitive: false },
    length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false },
    format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create]

  def index
    if signed_in?
      @post = current_user.posts.build
    elsif
      @user = User.new
    end
    @posts = Post.list.paginate(page: params[:page], per_page: 10)
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html do
          flash[:success] = "Posted!"
          redirect_to root_path
        end
        format.json { render json: { success: true, post: @post }, status: :created, location: @post }
        format.js
      else
        format.json { render json: { success: false, errors: @post.errors } }
        format.html { render 'new' }
      end
    end
  end

  private
  def post_params
    params.require(:post).permit(:url, :title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if params[:voter]
      flash.now[:notice] = "Please sign in before you vote."
    end
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    respond_to do |format|
      if user && user.authenticate(params[:session][:password])
        sign_in user
        flash[:success] = "Hey you, welcome back!"
        format.html do
          redirect_back_or root_path
        end

        format.json { render json: { success: true }, status: :created, location: user }
        format.js
      else
        format.json { render json: { success: false, error_message: "Invalid email/password combo!" },
          status: :created, location: user }
        format.html do
          flash.now[:error] = "Invalid email/password combo!"
          render 'new'
        end
      end
    end
  end

  def destroy
    sign_out
    flash[:success] = "Successfully signed out."
    redirect_to root_path
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        sign_in @user
        flash[:success] = "Welcome to newmakersPH!"
        format.html { redirect_to root_path }
        format.json { render json: { success: true, user: @user }, status: :created, location: @user }
        format.js
      else
        format.json { render json: { success: false, errors: @user.errors } }
        format.html { render 'new' }
      end
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :signed_in_user

  def create
    @post = Post.find(params[:vote][:post_id])
    @post.vote_from!(current_user)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "newsmakersPH"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(remember_token: cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def redirect_back_or(default)
    redirect_to (session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
<small>
    <a href="#">newsmakersPH</a>
</small>
<nav>
  <ul>
    <li><%= link_to "About", "#" %></li>
  </ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row">
    <div class="span10 offset1">
      <div class="pull-left">
        <%= render 'posts/submit_button' %>
        <%= link_to "newsmakersPH", root_path, id: "logo" %>
      </div>
      <span id="flash-holder">
        <% flash.each do |key, value| %>
          <%= content_tag(:span, value, class: "offset1 short-alert short-alert-#{key}") %>
        <% end %>
      </span>
      <div class="pull-right">
        <div class="btn-group">
          <%= render 'users/user_buttons' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/posts/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>                                                 

<%= f.label :title %>                               
<%= f.text_field :title %>  

<%= f.label :url %>                                
<%= f.text_field :url %>                            

<%= f.label "About" %>                            
<%= f.text_area :content %>                   

app/views/posts/_post.html.erb
<li>
  <div class="points">
    <%= render 'vote_form', post: post %>
  </div>
  <div class="post">
    <span class="title"><%= link_to post.title, post.url, target: "_blank" %></span>
    <span class="details">
      by <%= link_to post.user.username, post.user %> <%= time_ago_in_words(post.created_at) %> ago <span class="pull-right"><%= URI.parse(post.url).host.sub(/\Awww\./, '') %></span>
    </span>
  </div>
</li>

app/views/posts/_signin.html.erb
<div class="btn-group">
  <a href="#signin-modal" role="button" data-toggle="modal" class="anchor-button-small alizarin rounded1">
    <i class="icon-2x icon-circle-arrow-up"></i>
    <span><%= post.upvote %></span>
  </a>
  <a class="anchor-button-narrow concrete rounded1" href="#"><i class="icon-comments icon-large"></i></a>
</div>

app/views/posts/_submit_button.html.erb
<% if signed_in? %>
  <a href="#submit-modal" role="button" data-toggle="modal" class="left anchor-button-medium pomegranate rounded1">
    <i class="icon-2x icon-cloud-upload"></i>
      <span>SUBMIT</span>
  </a>
<% else %>
  <a href="#signin-modal" role="button" data-toggle="modal" class="left anchor-button-medium pomegranate rounded1">
    <i class="icon-2x icon-cloud-upload"></i>
      <span>SUBMIT</span>
  </a>
<% end %>

app/views/posts/_submit_modal.html.erb
<% if signed_in? %>
  <div id="submit-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="submit-modal-label" aria-hidden="true">
    <%= form_for(@post, remote: true) do |f| %>
      <div class="modal-header">
        <a class="close" data-dismiss="modal" aria-hidden="true">×</a>
        <h3 id="submit-modal-label" class="modal-label">New Post</h3>
      </div>
      <div class="modal-body">
        <div id="submit-errors" class="modal-errors">
        </div>
        <p>Enter a url of a news article, video, blog, gif, facebook post, or basically anything you want to trend.</p>
        <%= render 'posts/fields', f: f %>
      </div>
      <div class="modal-footer">
        <a class="anchor-button-medium anchor-fix concrete rounded1" data-dismiss="modal" aria-hidden="true">Close</a>
        <%= f.submit "Submit", class: "anchor-button-medium alizarin rounded1", id: "submit-btn" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/_vote.html.erb
<%= form_for(post.votes.build(post_id: post.id), remote:true) do |f| %>
  <div><%= f.hidden_field :post_id %></div>
  <div class="btn-group">
    <%= button_tag(type: 'submit', class: "button-small alizarin rounded1") do %>
      <i class="icon-2x icon-circle-arrow-up"></i>
      <span><%= post.upvote %></span>
    <% end %>
    <%= button_tag(disabled: true, class: "button-narrow concrete rounded1") do %>
      <i class="icon-large icon-comments"></i>
    <% end %>
  </div>
<% end %>

app/views/posts/_vote_form.html.erb
<div id="vote_form_<%= post.id %>">
  <% if signed_in? && post.voted_by?(current_user) %>
    <%= render 'voted', post: post %>
  <% elsif signed_in? %>
    <%= render 'vote', post: post %>
  <% else %>
    <%= render 'signin', post: post %>
  <% end %>
</div>

app/views/posts/_voted.html.erb
<div class="btn-group">
  <a href="#" class="anchor-button-small asbestos rounded1">
    <i class="icon-large icon-ok"></i>
    <span><%= post.upvote %></span>
  </a>
  <a class="anchor-button-narrow concrete rounded1" href="#"><i class="icon-comments icon-large"></i></a>
</div>

app/views/posts/create.js.erb
$("#submit-btn").attr('value', 'Submit')
$('#submit-modal').modal('hide')
$('#flash-holder').attr('class', 'offset1 short-alert short-alert-success').text("Posted!").fadeIn(1000).fadeOut(3000)
$("<%= escape_javascript(render(partial: 'post', locals: { post: @post })) %>").hide().prependTo('#posts').slideDown('slow')

app/views/posts/index.html.erb
<%= render 'posts/submit_modal' %>
<%= render 'users/signup_modal' %>
<%= render 'sessions/signin_modal' %>

<div class="row">
  <div class="span10 offset1">
    <ol id="posts" class="posts">
      <%= render @posts %>
    </ol>
    <%= will_paginate @posts %>
  </div>
</div>

app/views/posts/index.js.erb
$('#posts').append('<%= j render(@posts) %>');                
<% if @posts.next_page %>                                        
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>                                                          
  $('.pagination').remove();                                        
<% end %>                                                           
<% sleep 1 %>                                                       

app/views/posts/new.html.erb
<% provide(:title, "Submit") %>
<h1>Submit</h1>

<div class="row">
  <div class="span6 offset3">
    <p>Enter a url of a news article, video, blog, gif, facebook post, or basically anything you want to trend.</p>
    <%= form_for(@post) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
  </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<h1>Trending PH</h1>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>                                                 

 <%= f.label :username %>                                
 <%= f.text_field :username%>                            

 <%= f.label :email %>                               
 <%= f.text_field :email %>                          

 <%= f.label :password %>                            
 <%= f.password_field :password %>                   

 <%= f.label :password_confirmation, "Confirm Password" %>                                               
 <%= f.password_field :password_confirmation %>      

app/views/users/_signup_modal.html.erb
<% if !signed_in? %>
  <div id="signup-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="signup-modal-label" aria-hidden="true">
    <%= form_for(@user, remote: true) do |f| %>
      <div class="modal-header">
        <a class="close" data-dismiss="modal" aria-hidden="true">×</a>
        <h3 id="signup-modal-label" class="modal-label">Sign up</h3>
      </div>
      <div class="modal-body">
        <div id="signup-errors" class="modal-errors"></div>
        <p>Be a newsmaker.</p>
        <%= render 'users/fields', f: f %>
      </div>
      <div class="modal-footer">
        <a class="anchor-button-medium anchor-fix concrete rounded1" data-dismiss="modal" aria-hidden="true">Close</a>
        <%= f.submit "Sign up", class: "anchor-button-medium alizarin rounded1", id: "signup-btn" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/_user_buttons.html.erb
<% if signed_in? %>
  <%= link_to user_path(current_user), class: "anchor-button-narrow asbestos rounded1", title: "Profile"  do %>
    <i class="icon-large icon-user"></i>
  <% end %>
  <%= link_to signout_path, method: "delete", class: "anchor-button-narrow concrete rounded1", title: "Sign out" do %>
    <i class="icon-large icon-signout"></i>
  <% end %>
<% else %>
  <a href="#signup-modal" role="button" data-toggle="modal" title="Sign up" class="left anchor-button-narrow asbestos rounded1">
    Sign up!
  </a>
  <a href="#signin-modal" role="button" data-toggle="modal" title="Sign in" class="left anchor-button-narrow concrete rounded1">
    <i class="icon-large icon-signin"></i>
  </a>
<% end %>

app/views/users/create.js.erb
$("#signup-btn").attr('value', 'Submit')
$('#signup-modal').modal('hide')
window.location.reload()

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
  <aside class="span4">
  <section>
  <h1>
    <%= @user.username %>
  </h1>
  </section>
  </aside>
</div>

app/views/votes/create.js.erb
$("#vote_form_<%= @post.id %>").html("<%= escape_javascript(render('posts/voted', post: @post)) %>")